/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import easter_egg.Beat;
import java.awt.Color;
import java.awt.Event;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author elias
 */
public class PrimeiraTela extends javax.swing.JFrame {

    /**
     * Creates new form PrimeiraTela
     */
    
    private static Point point = new Point();
    public static int beat = 0;
    public PrimeiraTela() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                    point.x = e.getX();
                    point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
        jb_login.setBackground(new Color(1,1,1,0));
        jb_pn_login.setBackground(new Color(1,1,1,0));
        jb_pn_sobre.setBackground(new Color(1,1,1,0));
        jb_easter.setBackground(new Color(1,1,1,0));
        jb_minimizar.setBackground(new Color(1,1,1,0));
        jb_sair.setBackground(new Color(1,1,1,0));
        Telas(true,false,false);
    }
    
    /*public Point getLocation(){
        return this.getLocation();
    }
    
    public void setLocation(int x, int y){
        this.setLocation(x, y);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jp_interno_inicial = new javax.swing.JPanel();
        jp_acaoes = new javax.swing.JPanel();
        jp_minimizar = new javax.swing.JPanel();
        jb_minimizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jb_sair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jp_inicial = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jp_login = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TxtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jp_efetuar_login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jb_login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jp_sobre = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_easter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbBTSOBRE = new javax.swing.JPanel();
        jb_pn_sobre = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jpBTLOGIN = new javax.swing.JPanel();
        jb_pn_login = new javax.swing.JButton();
        txtBt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        jpPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_interno_inicial.setBackground(new java.awt.Color(0, 102, 204));
        jp_interno_inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_acaoes.setBackground(new java.awt.Color(51, 51, 51));

        jp_minimizar.setBackground(new java.awt.Color(51, 51, 51));
        jp_minimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_minimizar.setBorder(null);
        jb_minimizar.setOpaque(false);
        jb_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_minimizarActionPerformed(evt);
            }
        });
        jp_minimizar.add(jb_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jLabel9.setFont(new java.awt.Font("Candy Beans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_");
        jp_minimizar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_sair.setBorder(null);
        jb_sair.setOpaque(false);
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });
        jPanel4.add(jb_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        jLabel10.setFont(new java.awt.Font("Candy Beans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("X");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        javax.swing.GroupLayout jp_acaoesLayout = new javax.swing.GroupLayout(jp_acaoes);
        jp_acaoes.setLayout(jp_acaoesLayout);
        jp_acaoesLayout.setHorizontalGroup(
            jp_acaoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_acaoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jp_acaoesLayout.setVerticalGroup(
            jp_acaoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_minimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_interno_inicial.add(jp_acaoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 40));

        jp_inicial.setBackground(new java.awt.Color(0, 102, 204));

        jLabel8.setFont(new java.awt.Font("Candy Beans", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bem Vindo(a)!");

        javax.swing.GroupLayout jp_inicialLayout = new javax.swing.GroupLayout(jp_inicial);
        jp_inicial.setLayout(jp_inicialLayout);
        jp_inicialLayout.setHorizontalGroup(
            jp_inicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_inicialLayout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jp_inicialLayout.setVerticalGroup(
            jp_inicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inicialLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jp_interno_inicial.add(jp_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jp_login.setBackground(new java.awt.Color(0, 102, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        TxtSenha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtSenha.setBorder(null);
        TxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenhaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("LOGIN:");

        txtLogin.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setBorder(null);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("SENHA:");

        jp_efetuar_login.setBackground(new java.awt.Color(51, 51, 51));
        jp_efetuar_login.setForeground(new java.awt.Color(255, 255, 255));
        jp_efetuar_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_efetuar_loginMouseClicked(evt);
            }
        });
        jp_efetuar_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        jp_efetuar_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, -1));

        jb_login.setBackground(new java.awt.Color(51, 255, 0));
        jb_login.setBorder(null);
        jb_login.setOpaque(false);
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        jp_efetuar_login.add(jb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Esqueci minha senha");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jp_efetuar_login, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel7)))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_efetuar_login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_loginLayout = new javax.swing.GroupLayout(jp_login);
        jp_login.setLayout(jp_loginLayout);
        jp_loginLayout.setHorizontalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        jp_loginLayout.setVerticalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_loginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jp_interno_inicial.add(jp_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jp_sobre.setBackground(new java.awt.Color(0, 102, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_easter.setBorder(null);
        jb_easter.setOpaque(false);
        jb_easter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_easterActionPerformed(evt);
            }
        });
        jPanel2.add(jb_easter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 30));

        jLabel6.setFont(new java.awt.Font("Candy Beans", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema desenvolvido por 1Elias");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, -1));

        javax.swing.GroupLayout jp_sobreLayout = new javax.swing.GroupLayout(jp_sobre);
        jp_sobre.setLayout(jp_sobreLayout);
        jp_sobreLayout.setHorizontalGroup(
            jp_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_sobreLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jp_sobreLayout.setVerticalGroup(
            jp_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_sobreLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jp_interno_inicial.add(jp_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jpPrincipal.add(jp_interno_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbBTSOBRE.setBackground(new java.awt.Color(0, 102, 204));
        jbBTSOBRE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_pn_sobre.setBorder(null);
        jb_pn_sobre.setOpaque(false);
        jb_pn_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pn_sobreActionPerformed(evt);
            }
        });
        jbBTSOBRE.add(jb_pn_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SOBRE");
        jbBTSOBRE.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        jpPrincipal.add(jbBTSOBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 184, 40));

        jpBTLOGIN.setBackground(new java.awt.Color(0, 102, 204));
        jpBTLOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_pn_login.setToolTipText("");
        jb_pn_login.setBorder(null);
        jb_pn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_pn_login.setDefaultCapable(false);
        jb_pn_login.setOpaque(false);
        jb_pn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pn_loginActionPerformed(evt);
            }
        });
        jpBTLOGIN.add(jb_pn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        txtBt1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtBt1.setForeground(new java.awt.Color(255, 255, 255));
        txtBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBt1.setText("LOGIN");
        txtBt1.setToolTipText("");
        jpBTLOGIN.add(txtBt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        jpPrincipal.add(jpBTLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 184, -1));

        getContentPane().add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void Login(){
        if(jp_efetuar_login.getBackground() == Color.RED){
            jp_efetuar_login.setBackground(new Color(51,51,51));
        }else{
            jp_efetuar_login.setBackground(Color.red);
        }
    }
    
    private void Telas(boolean v_inicial, boolean v_login, boolean v_sobre){
        jp_inicial.setVisible(v_inicial);
        jp_sobre.setVisible(v_sobre);
        jp_login.setVisible(v_login);
    }
    
    private void jp_efetuar_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_efetuar_loginMouseClicked
        // TODO add your handling code here:
        //efetuar login
        Login();
        
    }//GEN-LAST:event_jp_efetuar_loginMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:
        //
        Login();
    }//GEN-LAST:event_jb_loginMouseClicked

    private void TxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_TxtSenhaActionPerformed

    private void jb_pn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pn_loginActionPerformed
        // TODO add your handling code here:
        if(txtBt1.getText().equals("LOGIN")){
            Telas(false,true,false);
            txtBt1.setText("INICIO");
        }else{
            Telas(true,false,false);
            txtBt1.setText("LOGIN");
        }
    }//GEN-LAST:event_jb_pn_loginActionPerformed

    private void jb_pn_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pn_sobreActionPerformed
        // TODO add your handling code here:
        Telas(false,false,true);
    }//GEN-LAST:event_jb_pn_sobreActionPerformed

    private void jb_easterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_easterActionPerformed
        // TODO add your handling code here:
       if(PrimeiraTela.beat != 1 ){
        Beat bt = new Beat();
       bt.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                    point.x = e.getX();
                    point.y = e.getY();
            }
        });
        bt.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = bt.getLocation();
                bt.setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
       bt.setVisible(true);
        beat = 1;
       }
    }//GEN-LAST:event_jb_easterActionPerformed

    private void jb_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_minimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jb_minimizarActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "O administrador deve ser consultado!" , "ANIMAL - Esqueceu a senha", 3);
    }//GEN-LAST:event_jLabel7MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jbBTSOBRE;
    private javax.swing.JButton jb_easter;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_minimizar;
    private javax.swing.JButton jb_pn_login;
    private javax.swing.JButton jb_pn_sobre;
    private javax.swing.JButton jb_sair;
    private javax.swing.JPanel jpBTLOGIN;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jp_acaoes;
    private javax.swing.JPanel jp_efetuar_login;
    private javax.swing.JPanel jp_inicial;
    private javax.swing.JPanel jp_interno_inicial;
    private javax.swing.JPanel jp_login;
    private javax.swing.JPanel jp_minimizar;
    private javax.swing.JPanel jp_sobre;
    private javax.swing.JLabel txtBt1;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables

   
}
